app = "bilifeedbot"
primary_region = "nrt"
swap_size_mb = 1024

[build]

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    soft_limit = 50
    hard_limit = 100

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256