app = "bilifeedbot"
primary_region = "lhr"
swap_size_mb = 1024

[http_service]
  internal_port = 9000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
